---

- name: Install the php packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: apt_packages
  environment: env
  when: ansible_os_family == "Debian"
  tags: [packages,php,fpm]

- name: Copy the PHP configuration file
  ini_file: dest=/etc/php5/fpm/php.ini section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: php_config
  notify: 
   - restart php-fpm
  tags: [configuration,php,fpm]

- name: Copy the FPM configuration file
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/php-fpm.conf backup=yes
  notify: 
   - restart php-fpm
  tags: [configuration,php,fpm]

- name: Copy the POOL configurations
  template: src=pool.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item['pool']['name'] }}.conf backup=yes
  with_items: fpm_pools
  when: fpm_pools|lower != 'none'
  notify: 
   - restart php-fpm
  tags: [configuration,php,fpm]
